#!/bin/bash
clear
echo ""
if [ $USER != 'root' ]; then
 echo -e "[\e[1;31mError\e[0m] You must run this script as root only"
	exit 1
fi

 source /etc/os-release
if [[ "$ID" != 'debian' ]]; then
 echo -e "[\e[1;31mError\e[0m] This script is for Debian only, exting..." 
 exit 1
 
fi
clear
echo ""
printf "Please Enter OCS Panel Details:\n"
printf "Enter the correct information base from OCS panel MySQL Credentials. install OCS panel first before you run this script.\n\n"
read -p 'DATABASE USERNAME(root): ' -e user
read -p 'DATABASE root PASSWORD: ' -e pass
read -p 'DATABASE NAME: ' -e name
clear
function InsProfile(){
echo 'clear' > /etc/profile.d/xam.sh
echo 'echo '' > /var/log/syslog' >> /etc/profile.d/xam.sh
echo "echo '\**=======**\                  /**=======**/   ||==========================================||'" >> /etc/profile.d/xam.sh
echo "echo ' \**=======**\                /**=======**/    ||******************************************||'" >> /etc/profile.d/xam.sh
echo "echo '  \**=======**\              /**=======**/     ||=============||*****||*****||=============||'" >> /etc/profile.d/xam.sh
echo "echo '   \**=======**\            /**=======**/                     ||*****||*****||'" >> /etc/profile.d/xam.sh
echo "echo '    \**=======**\          /**=======**/                      ||*****||*****||'" >> /etc/profile.d/xam.sh
echo "echo '     \**=======**\        /**=======**/                       ||*****||*****||'" >> /etc/profile.d/xam.sh
echo "echo '      \**=======**\      /**=======**/                        ||*****||*****||'" >> /etc/profile.d/xam.sh
echo "echo '       \**=======**\    /**=======**/                         ||*****||*****||'" >> /etc/profile.d/xam.sh
echo "echo '        \**=======**\**/**=======**/                          ||*****||*****||'" >> /etc/profile.d/xam.sh
echo "echo '         \**=======******=======**/                           ||*****||*****||'" >> /etc/profile.d/xam.sh
echo "echo '         /**=======******=======**\            ===========    ||*****||*****||'" >> /etc/profile.d/xam.sh
echo "echo '        /**=======**/**\**=======**\           ||*******||    ||*****||*****||'" >> /etc/profile.d/xam.sh
echo "echo '       /**=======**/    \**=======**\          ||*******||    ||*****||*****||'" >> /etc/profile.d/xam.sh
echo "echo '      /**=======**/      \**=======**\         ||*******||    ||*****||*****||'" >> /etc/profile.d/xam.sh
echo "echo '     /**=======**/        \**=======**\        ||*******||    ||*****||*****||'" >> /etc/profile.d/xam.sh
echo "echo '    /**=======**/          \**=======**\       ||*******||    ||*****||*****||'" >> /etc/profile.d/xam.sh
echo "echo '   /**=======**/            \**=======**\      ||*******||====||*****||*****||'" >> /etc/profile.d/xam.sh
echo "echo '  /**=======**/              \**=======**\     ||***************************||'" >> /etc/profile.d/xam.sh
echo "echo ' /**=======**/                \**=======**\    ||**************************//'" >> /etc/profile.d/xam.sh
echo "echo '/**=======**/                  \**=======**\   +\=========================//'" >> /etc/profile.d/xam.sh
echo "echo 'Welcome to FASTVPN Panel by: XAMJYSS143' | lolcat" >> /etc/profile.d/xam.sh
echo "echo 'Script by: XAMJYSS143'" >> /etc/profile.d/xam.sh
}
function InsFiles(){
rm -rf /home/panel/html/view
rm -rf /home/panel/html/controller
rm -rf /home/panel/html/lib
rm -rf /home/panel/html/model
rm -rf /home/panel/html/config/route.php
rm -rf /home/panel/html/tmp/*
cd ~
mkdir fastvpn
cd fastvpn
rm -rf *
wget https://github.com/xamjyss143/ocspaneltemplate/raw/master/fastvpn.tar.gz && tar zxvf fastvpn.tar.gz
mv view /home/panel/html
mv controller /home/panel/html
mv model /home/panel/html
mv lib /home/panel/html
mv route.php /home/panel/html/config
mv server_reset.php /home/panel/html
cd
}
function InsReset(){
cat <<"EOF15"> /home/panel/html/server_reset.php
<?php
     \$servername = "localhost";
     \$username = "$user"; //db_username
     \$password = "$pass"; //db_password
     \$dbname = "$name"; //database_name
     
     // Create connection
     \$conn = new mysqli(\$servername, \$username, \$password, \$dbname);
     // Check connection
     if (\$conn->connect_error) {
         die("Connection failed: " . \$conn->connect_error);
     }

     \$update = "UPDATE server SET created = '0' WHERE id >= 1";
     \$result = mysqli_query(\$conn, \$update);
     
?>
EOF15
}
echo -e "Configuring Profile..."
 InsProfile
echo -e "Moving Files to Directories"
 InsFiles
echo -e "Configuring Server Reset"
 InsReset
mysql -e "USE $name 
ALTER TABLE server ADD created varchar(255) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT '0'"

     timedatectl set-timezone Asia/Manila
     #write out current crontab
     crontab -l > mycron
     #echo new cron into cron file
     echo "0 0 * * * php /home/panel/html/server_reset.php" >> mycron
     #install new cron file
     crontab mycron
     service cron restart
     apt-get install lolcat
     gem install lolcat
     chmod -R 705 /home/panel/html/*
     chmod -R 755 /home/panel/html/tmp
     echo '0 0 * * * php /home/panel/html/server_reset.php' >> /etc/cron.d/mycron
clear
echo ""
bash /etc/profile.d/xam.sh
echo "Installation Success !"
echo "FASTVPN BY XAMJYSS143 Successfully Installed"


